Reviewed all french translation
Marx314/ASVS pull request #2
Opened 2020-06-15 18:52 UTC by chamorin

This Pull Request relates to issue [#805](https://github.com/OWASP/ASVS/issues/805)

2020-06-15 20:47 UTC, Marx314 requested changes
Il y a aussi plusieurs endroit ou "test de pénétration" n'a pas été changé, je ne sais pas si c'est une omission?

2020-06-15 20:47 UTC, Marx314 commented on 4.0/fr/0x13-V5-Validation-Sanitization-Encoding.md
> -| **5.5.2** | Vérifiez que l'application restreint correctement les analyseurs XML pour n'utiliser que la configuration la plus restrictive possible et pour s'assurer que les fonctions dangereuses te
> pour empêcher XXE 

ça fait sec un peu à lire?

2020-06-16 20:36 UTC, chamorin commented on 4.0/fr/0x13-V5-Validation-Sanitization-Encoding.md
> -| **5.5.2** | Vérifiez que l'application restreint correctement les analyseurs XML pour n'utiliser que la configuration la plus restrictive possible et pour s'assurer que les fonctions dangereuses te
J'ai fais les changements. Cependant pour les tests d'intrusions/pénétrations c'était voulu car à certain endroit ca sonnait bizarre

2020-06-17 14:11 UTC, Marx314 reviewed
:+1:

2020-06-17 14:11 UTC, merged